  steps:
    # Build the container image
    - name: 'gcr.io/cloud-builders/docker'
      args: ['buildx', 'build', '--platform', 'linux/amd64' '-t', 'gcr.io/cs3219-peerprepg34/frontend', './frontend']

    # Push the container image to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/cs3219-peerprepg34/frontend']

    # Deploy container image to Cloud Run
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: gcloud
      args: ['run', 'deploy', 'frontend', '--image', 'gcr.io/cs3219-peerprepg34/frontend', '--region', 'asia-east1']