FROM node:16

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . ./

EXPOSE 8000


ARG ENV 
ARG ${ENV}
ARG ${DB_CLOUD_URI}
ARG ${JWT_SECRET}
ARG ${FROM_NAME}
ARG ${FROM_EMAIL}
ARG ${FROM_EMAIL_PW}

RUN npm test
CMD [ "npm", "start" ]
