# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Backend CI

on:
  push:
    branches: [ "user-service" ]
  pull_request:
    branches: [ "user-service" ]

env:
  ENV: PROD
  DB_CLOUD_URI: mongodb+srv://admin:admin123@cluster0.esazx24.mongodb.net/cs3219-project-user-service?retryWrites=true&w=majority
  JWT_SECRET: threedoorcabinet
  FROM_NAME: PeerPrep
  FROM_EMAIL: threedoorcabinet@gmail.com
  FROM_EMAIL_PW: ivxlghliklnbmhta

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./user-service
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "14.x"
        cache: 'npm'
        cache-dependency-path: './user-service/package-lock.json'
    - name: Start MongoDB v${{ matrix.mongodb-version }}
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: 6.0.7

    - run: npm install
    - run: npm run test
